---
require: rubocop-rspec
Layout/LineLength:
  Max: 200
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExampleLength:
  Max: 15
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Lint/MissingSuper:
  Exclude:
    - 'lib/database_adapter/**/*'
