module Lesson4
  module TrueWay
    class Config
      class ConfigurationError < StandardError
      end

      self.@db_adapter: untyped
      self.@l10n_path: String?
      self.@routes_path: String?

      attr_writer self.db_adapter: untyped
      attr_writer self.l10n_path: String?
      attr_writer self.routes_path: String?

      def self.configure: { (self) -> void } -> void
      def self.db_adapter: () -> untyped
      def self.l10n_path: () -> String
      def self.routes_path: () -> String
    end
  end
end
